// 公共数据文件，统一管理简历页面所有数据

export const personalInfo = {
  name: '李涵祺',
  gender: '男',
  age: 32,
  experience: 8,
  phone: '18729391167',
  email: '18729391167@163.com',
  education: '本科',
  position: 'web前端',
  location: '陕西西安',
  availability: '随时到岗'
};

export const education = [
  {
    school: '西北工业大学',
    major: '计算机科学与技术',
    start: '2017.3',
    end: '2019.7',
  },
  {
    school: '西安石油大学',
    major: '石油化工生产技',
    start: '2013.3',
    end: '2016.1',
  },
];

export const jobs = [
  {
    company: '上海圆擎信息科技有限公司',
    role: '前端工程师',
    time: '2021.11 - 至今',
    desc: '负责公司核心产品的前端开发工作，参与大型项目的架构设计和开发，推动前端技术栈升级和工程化建设。',
  },
  {
    company: '中软国际',
    role: '前端工程师',
    time: '2019.11 - 2021.11',
    desc: '参与多个企业级项目的前端开发，负责组件库开发和维护，优化页面性能和用户体验。',
  },
  {
    company: '姚舜智能科技有限公司',
    role: '前端工程师',
    time: '2017.6 - 2019.11',
    desc: '负责公司产品的前端界面开发，参与产品需求分析和设计，提升产品的用户交互体验。',
  },
];

export const projects = [
  {
    title: '星罗业务风控',
    time: '2021.11-2025.5',
    tech: ['Vue3', 'Vite', 'VueRouter', 'Pinia', 'Ssaa', 'Echarts', 'ElementPlus', 'Axios', '高德地图'],
    brief: '构建一套基于用户实体行为分析的风险管理系统，通过实时和离线数据分析技术，对用户操作行为进行多维度监控与风险评估，实现风险行为的快速发现、精准识别和全流程管理。',
    duty: '负责整个前端开发环境的工程化搭建和日常需求开发工作。',
    detail: `核心功能：\n1、实时监控与可视化工作台\n告警统计：展示实时告警数量、类型分布及处理状态。\n风险事件分析：按事件类型、严重等级展示统计数据，支持多维筛选。\n日志趋势监控：通过折线图监控日志量波动，支持异常检测。\n2、日志管理\nTopic管理：维护日志接收通道，通过Flink SQL实现定制化日志解析。\n日志接入监控：每隔1小时（8:00-20:00）检测Topic日志写入状态，5秒级实时获取Flink Job运行状态。\n日志可信性管理：基于URL提取Host，结合人工审核机制关联日志与应用归属。\n3、应用与接口管理\n应用自动识别：每日凌晨扩展未归属应用的Host数据，需人工审核绑定。\n接口唯一性标识：基于URL Path与应用ID标记接口，支持敏感操作识别（如登录、越权），人工标记特殊接口类型：敏感信息、登录行为、日志质量监测等。\n4、标签体系与风险规则\n27类风险标签：程序自动标记：异地操作、越权行为、运单异常等。人工标记：涉密查询、丢弃日志、权限变更等。黑白名单：按用户/IP配置规则例外策略，支持组级管理。\n5、告警与事件闭环\n告警去重与通知：消费Kafka告警流，实现去重、静默、分级通知。事件全生命周期管理：从安全事件上报、升级、调查到整改任务跟踪。风险管理：整合举报平台数据，关联分析员工及网点风险。\n6、数据管理与分析\n基础数据维护：网点地址、用户权限、云客服白名单等。多维查询：支持用户、IP、运单、批量数据的快速检索与关联分析。报表与导出：按条件生成图表、导出操作日志及告警数据。`,
  },
  {
    title: '星眸安全运营',
    time: '2022.9-2025.5',
    tech: ['Vue3', 'Vite', 'VueRouter', 'Pinia', 'Ssaa', 'Echarts', 'ElementPlus', 'Axios'],
    brief: '综合性的安全运营管理平台，主要用于监控和管理终端安全风险，提供全面的安全态势感知和风险处置功能。',
    duty: '负责整个前端开发环境的工程化搭建和日常需求开发工作。',
    detail: `核心功能：\n1、接口治理：企业级API接口安全治理，主要针对含有敏感信息（如身份证、手机号）的接口进行监控和管理。\n2、钓鱼邮件：对邮件的发件人名称/邮箱、邮件文本、附件、链接进行安全检测，对可疑邮件进行标记、拦截、提醒，主动防御。\n3、终端监管：企业级终端设备安全监控系统，实现对公司各部门终端设备的安全状态可视化管理。\n4、样本采集：程序文件安全监控系统，通过样本采集和分析保障企业IT环境安全。\n5、特征管理：通过特征库的维护和管理，提供精准的程序识别和安全管控能力。\n6、风险处置：针对具有风险的终端设备进行人工处理流程。`,
  },
  {
    title: 'yto-design（业务组件库）',
    time: '2022.5-2022.8',
    tech: ['vite', 'gulp', 'unbuild', 'rollup', 'nx', 'pnpm', 'release-it'],
    brief: '部门内部业务开发组件库，基于 ElementPlus，支持全局引入和按需引入，采用 monorepo 架构。',
    duty: '负责整个组件库开发环境搭建和部分业务组件的实现。',
    detail: `本项目采用 pnpm + monroepo 的方式进行架构，实现一仓多库子包的结构方式。实现了 docs 、play、ui 三部分核心系统。`,
  },
  {
    title: 'csp-ts-sdk',
    time: '',
    tech: ['rollup', 'nx', 'pnpm', 'release-it'],
    brief: '用于收集和上报用户行为数据的 TypeScript SDK，主要用于 SPA 场景下的 PV/EV 数据采集。',
    duty: '',
    detail: `核心功能：\n1、数据采集：页面访问(PV)数据采集、元素事件(EV)数据采集\n2、数据处理：统一的数据格式构建、用户信息获取、时间戳处理、重复数据过滤\n3、数据上报：XMLHttpRequest、sendBeacon`,
  },
  {
    title: '日照市出租车综合监测系统',
    time: '2017.6-2019.11',
    tech: ['Vue', 'Vuex', 'VueRouter', 'Axios', 'Echarts', 'leaflet', 'ElementUI', '百度地图'],
    brief: '对本地区运行得出租车进行24小时大数据实时监控，出租车/驾驶员信息查询，视频监控/历史轨迹回放，各项指标统计计算等功能，并通过大屏进行投放。',
    duty: '负责整个项目的全面开发',
    detail: '',
  },
  {
    title: 'MPIR',
    time: '2020.3-2021.11',
    tech: ['React', 'Redux', 'axios', 'React-Router'],
    brief: '银行客户行为分析系统',
    duty: '负责项目从 0 到 1 的前端工程搭建，长期功能迭代开发任务',
    detail: '',
  },
  {
    title: 'RSS',
    time: '2019.11-2021.11',
    tech: ['React', 'ReactBootstrap', 'Redux', 'React-Router', 'axios'],
    brief: '银行交易监控系统',
    duty: '负责项目构建，页面布局规划，公共组件开发，数据模型定义、UT技术的编写',
    detail: '',
  },
];

export const skillList = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'ES6',
  'Vue2',
  'Vue3',
  'React',
  'Bootstrap',
  'vue-router',
  'react-router',
  'Vuex',
  'Redux',
  'Pinia',
  'Axios',
  'JQuery',
  'Vite',
  'Webpack',
  'Rollup',
  'Gulp',
  'Unbuild',
  'Lerna',
  'NX',
  'Sass',
  'Less',
  'Unocss',
  'ElementPlus',
  'Antd',
  'Vant',
  'Echarts',
  'G2',
  'Leaflet',
  'GIT',
  'SVN',
  'SourceTree',
  'Cursor',
  'Monorepo',
  'eslint',
  'prettier',
  'commitlint',
  'husky',
  'lint-staged',
  'ca-git',
  'JS-SDK',
  'Angular',
  '小程序',
  'mpvue',
  'wepy',
  'mysql',
  'node.js',
  '.Net'
];

export const skillDetails = [
  '精通 HTML 语义化标签、结构布局、SEO 优化等。',
  '精通 CSS3，熟悉 Flex、Grid、动画、响应式布局等。',
  '精通 JavaScript，掌握原型链、闭包、异步编程、DOM/BOM 操作等。',
  '熟练使用 TypeScript，类型系统、泛型、类型推断等。',
  '熟悉 ES6+ 新特性，如解构、箭头函数、Promise、模块化等。',
  '熟练使用 Vue2，掌握组件化、生命周期、指令、插件开发等。',
  '熟练使用 Vue3，掌握 Composition API、响应式原理、TS 支持等。',
  '熟练使用 React，掌握 Hooks、Context、组件通信、性能优化等。',
  '熟悉 Bootstrap，能快速搭建响应式页面。',
  '熟练使用 vue-router，掌握路由守卫、动态路由、懒加载等。',
  '熟练使用 react-router，掌握路由嵌套、动态路由、导航守卫等。',
  '熟练使用 Vuex，掌握状态管理、模块化、插件等。',
  '熟练使用 Redux，掌握中间件、异步流、Redux Toolkit 等。',
  '熟练使用 Pinia，掌握新一代 Vue 状态管理。',
  '熟练使用 Axios，掌握请求拦截、错误处理、并发请求等。',
  '熟悉 JQuery，能快速实现 DOM 操作、动画、Ajax 等。',
  '熟练使用 Vite，掌握配置优化、插件开发、性能提升等。',
  '熟练使用 Webpack，掌握 Loader、Plugin、Tree Shaking、代码分割等。',
  '熟悉 Rollup，掌握库打包、按需加载等。',
  '熟悉 Gulp，掌握自动化构建流程。',
  '熟悉 Unbuild，了解现代打包工具链。',
  '熟悉 Lerna，掌握多包管理、发布流程。',
  '熟悉 NX，了解大型项目工程化管理。',
  '熟悉 Sass，掌握嵌套、变量、mixin、函数等。',
  '熟悉 Less，掌握变量、嵌套、运算等。',
  '熟悉 Unocss，了解原子化 CSS 方案。',
  '熟练使用 ElementPlus，能高效开发后台管理系统。',
  '熟练使用 Antd，能高效开发企业级中后台系统。',
  '熟悉 Vant，能开发移动端 H5 页面。',
  '熟悉 Echarts，能实现复杂数据可视化。',
  '熟悉 G2，了解数据可视化方案。',
  '熟悉 Leaflet，能实现地图可视化。',
  '熟练使用 GIT，掌握分支管理、冲突解决、协作流程等。',
  '熟悉 SVN，了解版本管理。',
  '熟悉 SourceTree，图形化管理代码。',
  '熟练使用 Cursor，AI 辅助高效开发。',
  '熟悉 Monorepo 架构，能搭建多包项目基础框架。',
  '熟练配置 eslint，代码规范自动校验。',
  '熟练配置 prettier，代码自动格式化。',
  '熟悉 commitlint，规范提交信息。',
  '熟悉 husky，自动化 Git 钩子管理。',
  '熟悉 lint-staged，提升代码提交质量。',
  '熟悉 ca-git，了解企业级 Git 流程。',
  '能独立开发业务组件库、JS-SDK 等。',
  '了解 Angular 框架。',
  '了解小程序开发流程。',
  '了解 mpvue、wepy 等小程序框架。',
  '了解 mysql 数据库基本操作。',
  '了解 node.js 服务端开发。',
  '了解 .Net 基础知识。'
];